import { useState } from 'react'
import { motion } from 'motion/react'
import { FileSpreadsheet, Download } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { GlassCard, Button, Input, Select, Label, DataTable, Badge, PageHeader } from '@/components/shared'
import type { Column } from '@/components/shared'
import { tripsService } from '@/services/trips.service'
import { fuelService } from '@/services/fuel.service'
import { payrollService } from '@/services/payroll.service'
import { todayISO } from '@/lib/utils'

const recentCols: Column[] = [
  { label: 'Report Name', key: 'name', render: (v) => <span className="font-bold">{String(v)}</span> },
  { label: 'Category', key: 'category', render: (v) => <Badge variant="info">{String(v)}</Badge> },
  { label: 'Date Range', key: 'range' },
  { label: 'Generated By', key: 'user' },
  { label: 'Format', key: 'format', render: (v) => <Badge variant={v === 'PDF' ? 'danger' : 'success'}>{String(v)}</Badge> },
]

const CATEGORIES = [
  { label: 'Trip Analytics', desc: 'Expenses, income, route-wise summary' },
  { label: 'Fuel Consumption', desc: 'Day-wise, bus-wise, driver-wise' },
  { label: 'Payroll Summary', desc: 'Salary statements and disbursals' },
  { label: 'Laundry Statement', desc: 'Vendor-wise laundry reconciliation' },
  { label: 'Garage Maintenance', desc: 'Repair costs and job card history' },
  { label: 'Booking Report', desc: 'PNR-wise booking and collection data' },
  { label: 'Trial Balance', desc: 'Accounting debit/credit balance' },
  { label: 'P&L Statement', desc: 'Profit and loss for the period' },
]

const today = todayISO()

export default function ReportsPage() {
  const [form, setForm] = useState({ category: 'Trip Analytics', from_date: '', to_date: todayISO(), format: 'PDF' })

  const handleGenerate = () => {
    if (!form.from_date) { toast.error('Please select a date range'); return }
    toast.success(`Generating ${form.category} report as ${form.format}...`)
  }

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
      <PageHeader title="Analytics & Reports" subtitle="Generate and download comprehensive business reports" />

      <GlassCard className="p-6" colorBar="bg-gradient-to-r from-blue-400 to-emerald-400">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2"><FileSpreadsheet className="w-5 h-5 text-emerald-500" /> Report Generator</h2>
          <Button onClick={handleGenerate}><Download className="w-4 h-4" /> Generate & Download</Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-5">
          <div><Label>Report Category</Label>
            <Select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>
              {CATEGORIES.map(c => <option key={c.label} value={c.label}>{c.label}</option>)}
            </Select></div>
          <div><Label>From Date</Label><Input type="date" max={today} value={form.from_date} onChange={(e) => setForm({ ...form, from_date: e.target.value })} /></div>
          <div><Label>To Date</Label><Input type="date" max={today} value={form.to_date} onChange={(e) => setForm({ ...form, to_date: e.target.value })} /></div>
          <div><Label>Format</Label>
            <Select value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value })}>
              <option>PDF</option><option>Excel</option>
            </Select></div>
        </div>
      </GlassCard>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {CATEGORIES.map((c) => (
          <GlassCard
            key={c.label}
            className="p-5 hover:border-blue-300 cursor-pointer"
            onClick={() => setForm({ ...form, category: c.label })}
          >
            <div className={`w-8 h-8 rounded-xl mb-3 flex items-center justify-center ${form.category === c.label ? 'bg-blue-100' : 'bg-slate-100'}`}>
              <FileSpreadsheet className={`w-4 h-4 ${form.category === c.label ? 'text-blue-600' : 'text-slate-500'}`} />
            </div>
            <div className={`font-bold text-sm ${form.category === c.label ? 'text-blue-600' : 'text-slate-800'}`}>{c.label}</div>
            <div className="text-xs text-slate-500 mt-0.5">{c.desc}</div>
          </GlassCard>
        ))}
      </div>

      <DataTable
        title="Recently Generated Reports"
        columns={recentCols}
        data={[
          { name: 'Monthly Trip Analytics', category: 'Trip Analytics', range: '01 May - 31 May 2025', user: 'Prakash', format: 'PDF' },
          { name: 'Fuel Consumption Q1', category: 'Fuel Consumption', range: 'Jan-Mar 2025', user: 'SUDHEER', format: 'Excel' },
          { name: 'Salary Statement Oct', category: 'Payroll Summary', range: 'Oct 2025', user: 'Sai', format: 'PDF' },
        ]}
        onAction={() => {}}
        actions={['view', 'pdf', 'print']}
      />
    </motion.div>
  )
}
